### ISSUE TITLE
Plugin doesn't actually work

### ISSUE THREAD

**Issue by aaron-em** [kauegimenes/jquery-lock#1]
![plugin doesn t actually work](https://cloud.githubusercontent.com/assets/5650970/14569829/06cf10de-030f-11e6-86c7-b7271ed8759b.PNG)

What's the point?

**Comment by kaue** [comment]
@aaron-em The idea of the plugin is to prevent users without technical background from changing the page HTML. For example. many eCommerce customers change the price of the product using dev tools and send a screenshoot.
