### ISSUE TITLE
it's very easy to remove the events on the locked content.

### ISSUE THREAD

**Issue by mohitleo9** [kauegimenes/jquery-lock#2]
I think that it's very hard to have such a plugin. All it does is make it a little more difficult for the people to change the content. All you have to do is remove the event listener that is responsible for securing the value of the content. chrome event provides a button to delete the event (DOMSubtreeModified).

**Comment by sirwolfgang** [comment]
But that is given that you know its being locked, and how it works. In a blackbox environment, with a decently sized code base, this detail is easy to overlook. This could work pretty well at stopping some script kiddie XSS or hijacking iframe.

**Comment by kaue** [comment]
@mohitleo9 @sirwolfgang The idea of the plugin is to prevent users with no technical background from changing the page HTML. For example. many eCommerce customers change the price of the product using dev tools and send a screenshoot.
